export const requestRobotsActionTypes = {
    REQUEST_ROBOTS_PENDING: 'REQUEST_ROBOTS_PENDING',
    REQUEST_ROBOTS_SUCCESS: 'REQUEST_ROBOTS_SUCCESS',
    REQUEST_ROBOTS_FAILED: 'REQUEST_ROBOTS_FAILED'
}